/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ESlugIndexRouteImport } from './routes/e.$slug.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ESlugSummaryRouteImport } from './routes/e.$slug.summary'
import { Route as ESlugRsvpRouteImport } from './routes/e.$slug.rsvp'
import { Route as ESlugMessagesRouteImport } from './routes/e.$slug.messages'
import { Route as ESlugMemoriesRouteImport } from './routes/e.$slug.memories'
import { Route as ESlugLiveRouteImport } from './routes/e.$slug.live'
import { Route as ESlugGalleryRouteImport } from './routes/e.$slug.gallery'
import { Route as AuthenticatedAppEventsNewRouteImport } from './routes/_authenticated/app.events.new'
import { Route as AuthenticatedAppEventsIdRouteImport } from './routes/_authenticated/app.events.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ESlugIndexRoute = ESlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ESlugRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ESlugSummaryRoute = ESlugSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => ESlugRoute,
} as any)
const ESlugRsvpRoute = ESlugRsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => ESlugRoute,
} as any)
const ESlugMessagesRoute = ESlugMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ESlugRoute,
} as any)
const ESlugMemoriesRoute = ESlugMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => ESlugRoute,
} as any)
const ESlugLiveRoute = ESlugLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ESlugRoute,
} as any)
const ESlugGalleryRoute = ESlugGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ESlugRoute,
} as any)
const AuthenticatedAppEventsNewRoute =
  AuthenticatedAppEventsNewRouteImport.update({
    id: '/events/new',
    path: '/events/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEventsIdRoute =
  AuthenticatedAppEventsIdRouteImport.update({
    id: '/events/$id',
    path: '/events/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/e/$slug': typeof ESlugRouteWithChildren
  '/r/$slug': typeof RSlugRoute
  '/e/$slug/gallery': typeof ESlugGalleryRoute
  '/e/$slug/live': typeof ESlugLiveRoute
  '/e/$slug/memories': typeof ESlugMemoriesRoute
  '/e/$slug/messages': typeof ESlugMessagesRoute
  '/e/$slug/rsvp': typeof ESlugRsvpRoute
  '/e/$slug/summary': typeof ESlugSummaryRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/e/$slug/': typeof ESlugIndexRoute
  '/app/events/$id': typeof AuthenticatedAppEventsIdRoute
  '/app/events/new': typeof AuthenticatedAppEventsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/r/$slug': typeof RSlugRoute
  '/e/$slug/gallery': typeof ESlugGalleryRoute
  '/e/$slug/live': typeof ESlugLiveRoute
  '/e/$slug/memories': typeof ESlugMemoriesRoute
  '/e/$slug/messages': typeof ESlugMessagesRoute
  '/e/$slug/rsvp': typeof ESlugRsvpRoute
  '/e/$slug/summary': typeof ESlugSummaryRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/e/$slug': typeof ESlugIndexRoute
  '/app/events/$id': typeof AuthenticatedAppEventsIdRoute
  '/app/events/new': typeof AuthenticatedAppEventsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/e/$slug': typeof ESlugRouteWithChildren
  '/r/$slug': typeof RSlugRoute
  '/e/$slug/gallery': typeof ESlugGalleryRoute
  '/e/$slug/live': typeof ESlugLiveRoute
  '/e/$slug/memories': typeof ESlugMemoriesRoute
  '/e/$slug/messages': typeof ESlugMessagesRoute
  '/e/$slug/rsvp': typeof ESlugRsvpRoute
  '/e/$slug/summary': typeof ESlugSummaryRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/e/$slug/': typeof ESlugIndexRoute
  '/_authenticated/app/events/$id': typeof AuthenticatedAppEventsIdRoute
  '/_authenticated/app/events/new': typeof AuthenticatedAppEventsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/e/$slug'
    | '/r/$slug'
    | '/e/$slug/gallery'
    | '/e/$slug/live'
    | '/e/$slug/memories'
    | '/e/$slug/messages'
    | '/e/$slug/rsvp'
    | '/e/$slug/summary'
    | '/app/'
    | '/e/$slug/'
    | '/app/events/$id'
    | '/app/events/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/r/$slug'
    | '/e/$slug/gallery'
    | '/e/$slug/live'
    | '/e/$slug/memories'
    | '/e/$slug/messages'
    | '/e/$slug/rsvp'
    | '/e/$slug/summary'
    | '/app'
    | '/e/$slug'
    | '/app/events/$id'
    | '/app/events/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/e/$slug'
    | '/r/$slug'
    | '/e/$slug/gallery'
    | '/e/$slug/live'
    | '/e/$slug/memories'
    | '/e/$slug/messages'
    | '/e/$slug/rsvp'
    | '/e/$slug/summary'
    | '/_authenticated/app/'
    | '/e/$slug/'
    | '/_authenticated/app/events/$id'
    | '/_authenticated/app/events/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ESlugRoute: typeof ESlugRouteWithChildren
  RSlugRoute: typeof RSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/e/$slug/': {
      id: '/e/$slug/'
      path: '/'
      fullPath: '/e/$slug/'
      preLoaderRoute: typeof ESlugIndexRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/e/$slug/summary': {
      id: '/e/$slug/summary'
      path: '/summary'
      fullPath: '/e/$slug/summary'
      preLoaderRoute: typeof ESlugSummaryRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/e/$slug/rsvp': {
      id: '/e/$slug/rsvp'
      path: '/rsvp'
      fullPath: '/e/$slug/rsvp'
      preLoaderRoute: typeof ESlugRsvpRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/e/$slug/messages': {
      id: '/e/$slug/messages'
      path: '/messages'
      fullPath: '/e/$slug/messages'
      preLoaderRoute: typeof ESlugMessagesRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/e/$slug/memories': {
      id: '/e/$slug/memories'
      path: '/memories'
      fullPath: '/e/$slug/memories'
      preLoaderRoute: typeof ESlugMemoriesRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/e/$slug/live': {
      id: '/e/$slug/live'
      path: '/live'
      fullPath: '/e/$slug/live'
      preLoaderRoute: typeof ESlugLiveRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/e/$slug/gallery': {
      id: '/e/$slug/gallery'
      path: '/gallery'
      fullPath: '/e/$slug/gallery'
      preLoaderRoute: typeof ESlugGalleryRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/_authenticated/app/events/new': {
      id: '/_authenticated/app/events/new'
      path: '/events/new'
      fullPath: '/app/events/new'
      preLoaderRoute: typeof AuthenticatedAppEventsNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/events/$id': {
      id: '/_authenticated/app/events/$id'
      path: '/events/$id'
      fullPath: '/app/events/$id'
      preLoaderRoute: typeof AuthenticatedAppEventsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppEventsIdRoute: typeof AuthenticatedAppEventsIdRoute
  AuthenticatedAppEventsNewRoute: typeof AuthenticatedAppEventsNewRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppEventsIdRoute: AuthenticatedAppEventsIdRoute,
  AuthenticatedAppEventsNewRoute: AuthenticatedAppEventsNewRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ESlugRouteChildren {
  ESlugGalleryRoute: typeof ESlugGalleryRoute
  ESlugLiveRoute: typeof ESlugLiveRoute
  ESlugMemoriesRoute: typeof ESlugMemoriesRoute
  ESlugMessagesRoute: typeof ESlugMessagesRoute
  ESlugRsvpRoute: typeof ESlugRsvpRoute
  ESlugSummaryRoute: typeof ESlugSummaryRoute
  ESlugIndexRoute: typeof ESlugIndexRoute
}

const ESlugRouteChildren: ESlugRouteChildren = {
  ESlugGalleryRoute: ESlugGalleryRoute,
  ESlugLiveRoute: ESlugLiveRoute,
  ESlugMemoriesRoute: ESlugMemoriesRoute,
  ESlugMessagesRoute: ESlugMessagesRoute,
  ESlugRsvpRoute: ESlugRsvpRoute,
  ESlugSummaryRoute: ESlugSummaryRoute,
  ESlugIndexRoute: ESlugIndexRoute,
}

const ESlugRouteWithChildren = ESlugRoute._addFileChildren(ESlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ESlugRoute: ESlugRouteWithChildren,
  RSlugRoute: RSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
